name: Notify Discord on PR Comment

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]   

env:
  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    if: github.event != null
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up jq
        run: sudo apt-get install jq
        
      - name: Debag Send notification to Discord
        run: |
          COMMENT_BODY="@user1 @user2 @user-three Let's check this!"
          GITHUB_USERNAMES=$(echo "$COMMENT_BODY" | grep -oP '@[\w.-]+' || echo "")

          echo "$COMMENT_BODY"

          if [ -z "$GITHUB_USERNAMES" ]; then
            echo "No mentions found in the comment."
            exit 0
          fi

          # どうやらここが複数の@を1行の空白区切りに整えてくれるらしい
          DISCORD_USER_IDS=$(echo "$GITHUB_USERNAMES" | while read -r GITHUB_USERNAME; do
          jq -r ".\"$GITHUB_USERNAME\" // \"\"" < ./sample.json
          done | tr '\n' ' ')

          echo "$DISCORD_USER_IDS"

          # Discordで紐付けされたアカウントのメンションが見つかった場合のみ通知を送信
          if [ -n "$DISCORD_USER_IDS" ]; then
          
            #複数メンションのために取り付け
            MENTION_STRING=$(echo "$DISCORD_USER_IDS"| xargs | sed 's/ /> <@/g')
            MENTION_STRING="<@$MENTION_STRING>"
            #ここまで
            echo "Mention found, sending notification to <@$DISCORD_USER_IDS>..."
            echo "$MENTION_STRING"

          else
            echo "No valid GitHub username found, skipping notification."
          fi
      

